lab50:
  window:
    - editor
    - readme
    - terminal
    - browser
  files:
    - !include test.py 
  check50:
    checks:
      hello world:
        - run: python3 hello.py
          stdout: Hello, world!
          exit: 0


